---
# tasks file for maven
- name: Update and upgrade apt packages
  become: true
  apt:
   update_cache: yes

- name: Install python software properties
  apt: name=python-software-properties

- name: Add repository
  apt_repository:
   repo: ppa:webupd8team/java

- name: update cache
  shell: sudo apt-get update
  

- name:  Install jdk
  apt: pkg=default-jre state=installed update_cache=true

- name: download maven
  get_url:
     url: http://apache.mirror.digitalpacific.com.au/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
     dest: /home/edureka/Downloads
     mode: 0777
- name: Uncompress/tar the maven file
  shell: /bin/tar -xzvf /home/edureka/Downloads/apache-maven-3.3.9-bin.tar.gz -C /opt/

- name: Install maven
  shell: update-alternatives --install /usr/bin/mvn maven /opt/apache-maven-3.3.9/bin/mvn 1001

